version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx
    # image: gcr.io/bootingsi/nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - db

  server:
    container_name: clip-planet-server
    build:
      dockerfile: ./Dockerfile
    restart: always
    expose:
      - '5000'
    networks:
      - db-connection
      - server-connection
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: mysql-container
    networks:
      - db-connection
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
      MYSQL_DATA_DIR: /var/lib/mysql

networks:
  server-connection:
    driver: bridge
  db-connection:
    driver: bridge
